FROM node:22-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/prisma ./prisma
RUN npx prisma generate

COPY backend ./
RUN npm run build

EXPOSE 5000

CMD ["sh", "-c", "npx prisma db push && npm run seed && node dist/server.js"]
